######################################################################
# Automatically generated by qmake (3.0) Sun Sep 10 22:12:33 2017
######################################################################

TEMPLATE = app
TARGET = Fitting_Room
INCLUDEPATH += .
LIBS += -lwiringPi -lmosquitto
CONFIG -= warn_off
CONFIG += c++11

# Input
HEADERS += VideoButtons.h VideoControls.h VideoMQTT.h
SOURCES += Fitting_Room.cpp VideoButtons.cpp VideoControls.cpp VideoMQTT.cpp

QT -= gui
QT += dbus
